cep/urls.py
# -*- coding: utf-8 -*-
try:
    from django.conf.urls import url
except ImportError:  # deprecated since Django 1.4
    from django.conf.urls.defaults import patterns, url

from .views import addressGet

urlpatterns = [
    url(r'^(?P<zipcode>[\w-]+)/$', addressGet, name='address')
]

core/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
import django.contrib.auth.views as auth_views
import core.views.index as views
import core.views.utils as util_views
import core.views.first_configuration as fc_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='home'),
    # url(r'^index2/', views.index2, name='home2'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^cors_request/$', views.cors_request, name='cors_request'),
    url(r'^updateCities', views.update_cities, name='updateCities'),
    url(r'^accounts/login/$', auth_views.login, name="login"),
    url(r'^accounts/signup/$', views.signup, name="signup"),
    url(r'^browser_view/$', views.browser_view, name="browser_view"),
    url(r'^accounts/candidatesignup/(?P<uidb64>[0-9A-Za-z_\-]+)/$', views.candidate_signup, name="candidate_signup"),
    url(r'^accounts/logout/$', auth_views.logout, {'next_page': '/'}, name="logout"),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^dashboard/', include(('dashboard.urls', 'dashboard'), namespace='dashboard')),
    url(r'candidato/', include(('candidato.urls', 'candidato'), namespace='candidato')),
    url(r'^elections/', include(('elections.urls', 'elections'), namespace='elections')),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^cep/', include('cep.urls')),
    url(r'^account/firstsetup', views.firstsetup, name="firstsetup"),
    # the template update for the firstsetup
    url(r'^account/primeiroSetup', fc_views.primeiro_setup, name="primeiro_setup"),
    url(r'^account/add_team_member', fc_views.add_team_member, name='account_add_user_roles'),
    url(r'^account/add_committee', fc_views.add_committee, name='account_add_committee'),
    # email confirmation
    url(r'^account/account_accept_invite/(?P<uidb64>[0-9A-Za-z_\-]+)',
        fc_views.account_accept_invite,
        name='account_accept_invite'),
    url(r'^account/account_candidator_aprove_user/(?P<uidb64>[0-9A-Za-z_\-]+)',
        fc_views.account_candidator_aprove_user,
        name='account_candidator_aprove_user'),
    url(r'^account/account_accept_candidator_invite/(?P<uidb64>[0-9A-Za-z_\-]+)',
        fc_views.account_accept_candidator_invite,
        name='account_accept_candidator_invite'),
    # apis
    url(r'^account/check_username', views.check_username, name='check_username'),
    url(r'^account/check_email', views.check_email, name='check_email'),
    # password reset
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^approve_user/$', views.apporve_user, name='apporve_user'),
    url(r'^user_configuration', views.user_configuration, name='user_configuration'),
    url(r'^update_user_configuration/$', views.update_user_configuration, name='update_user_configuration'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^test404/', views.test404),
    url(r'^util/update/$', util_views.UtilView.as_view(), name='utils_candidate'),
    url(r'^util/copy_mongodb/$', util_views.CopyMongoDBView.as_view(), name='utils_copy_mongodb'),
    url(r'^test500/', views.test500),
] + static('settings.STATIC_URL', document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from __future__ import unicode_literals

from candidato.models import Candidate
from core.utils.model_utils import phone_validators
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver
from django_extensions.db.models import (TimeStampedModel,
                                         TitleSlugDescriptionModel)

event_hook_depth = 0

POLITICAL_PARTY_CHOICES = (
    ('pmdb', 'PMDB'),
    ('pt', 'PT'),
    ('psdb', 'PSDB'),
    ('pp', 'PP'),
    ('pdt', 'PDT'),
    ('dem', 'DEMOCRATAS'),
    ('pr', 'PR'),
    ('psb', 'PSB'),
    ('pps', 'PPS'),
    ('pcdob', 'PCdoB'),
    ('prb', 'PRB'),
    ('pv', 'PV'),
    ('psd', 'PSD'),
    ('prp', 'PRP'),
    ('psl', 'PSL'),
    ('pmn', 'PMN'),
    ('phs', 'PHS'),
    ('ptc', 'PTC'),
    ('sd', 'SOLIDARIEDADE'),
    ('psdC', 'PSDC'),
    ('avante', 'AVANTE'),
    ('podemos', 'PODE'),
    ('psol', 'PSOL'),
)

# Political Spectrum is the ideological posture of the Political Party
# (ex. democrats or republicans | left wing or right wing)
PoliticalSpectrum = (
    ('Centro', 'Centro'),
    ('CentroDireita', 'Centro Direita'),
    ('CentroEsquerda', 'Centro Esquerda'),
    ('Esquerda', 'Esquerda'),
    ('ExtremaDireita', 'Extrema Direita'),
    ('ExtremaEsquerda', 'Extrema Esquerda'),
)

# Regions In Brazil (used to define the State location (and Citie location)
Regioes = (
    (1, 'Norte'),   # north
    (2, 'Nordeste'),    # northeast
    (3, 'Sudeste'),    # southeast
    (4, 'Sul'),  # south
    (5, 'Centro-Oeste'),    # Midwest
)


# Manager for the Federal States in Brazil
class EstadoManager(models.Manager):
    def search(self, query):
        return self.get_queryset().filter(
            models.Q(Nome__icontains=query) | models.Q(Uf__icontains=query)
        )


# This is the Manager for the Cities (Conties) in Brazil
class MunicipioManager(models.Manager):
    def search(self, query):
        return self.get_queryset().filter(
            models.Q(Nome__icontains=query) | models.Q(Uf__icontains=query)
        )


# This is the Manager for the Candidate Political Party
class PoliticalPartiesManager(models.Manager):
    def search(self, query):
        return self.get_queryset().filter(
            models.Q(electoral_number__icontains=query) | models.Q(sigla__icontains=query)
        )


# Political Partie list
class PoliticalParties(models.Model):
    # id_partido = models.IntegerField("Numero Partido",primary_key=True, unique=True)
    sigla = models.CharField('Sigla', max_length=6)    # party symbol
    name = models.CharField('Nome do Partido', max_length=70)   # party complete name
    # the number that indicate the Political Party
    electoral_number = models.CharField("Número Eleitoral", max_length=3)
    affiliates_number = models.IntegerField("Número de Filiados")
    # The present political leader of the Political Party
    president_name = models.CharField("Presidente Atual", max_length=60)
    political_spectrum = models.CharField(max_length=100, choices=PoliticalSpectrum, blank=True, null=True)
    image_flag = models.ImageField(
        upload_to='images/political_flags', verbose_name='bandeiraPartido', null=True, blank=True
    )
    objects = PoliticalPartiesManager()

    def __str__(self):
        return self.sigla


# Table of Federal States in Brazil
class Estado (models.Model):
    # id = models.IntegerField("Numero Partido", primary_key=True, unique=True)
    CodigoUf = models.PositiveSmallIntegerField(primary_key=True, unique=True)
    Nome = models.CharField(max_length=50)
    Uf = models.CharField(max_length=2)
    Regiao = models.PositiveSmallIntegerField(blank=False)
    objects = EstadoManager

    def __str__(self):
        return self.Nome


# This is the conties database. All cities in Brasil
class Municipio(models.Model):
    # Id = models.IntegerField(primary_key=True, unique=True)
    Codigo = models.IntegerField(null=False, unique=True)   # unique Federal Code to the Region
    Nome = models.CharField(max_length=255)
    Uf = models.CharField(max_length=2)
    objects = MunicipioManager()

    def __str__(self):
        return self.Nome


# This is the Neiborhood locations, for the address forms and data location
class Bairro(models.Model):
    # Id = models.IntegerField(primary_key=True,unique=True)
    Codigo = models.CharField(max_length=10, unique=True)
    Nome = models.CharField(max_length=255, null=False)
    Uf = models.CharField(max_length=2)

    def __str__(self):
        return self.Nome


class RelationshipNetwork(models.Model):
    id_actor_a = models.IntegerField()  # index from the first actor
    kind_of_relationship = models.CharField("Tipo de Relacionamento", max_length=40, blank=True, null=True)
    id_actor_b = models.IntegerField()  # index from the second actor
    secondary_actor = models.IntegerField()
    kind_of_relationship_to_secondary = models.CharField("Tipo de Relacionamento", max_length=40, blank=True, null=True)
    observations = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.kind_of_relationship


GENDER_CHOICES = {
    'physical': (
        ("M", 'Masculino'),
        ("F", 'Feminino'),
        ("N", 'Outro'),
    ),

    'legal': (
        ("E", 'Empresa'),
        ("S", 'Sindicato'),
        ("O", 'Organização ou Instituto'),
    ),
}


# Marital Status
ESTADO_CIVIL_CHOICES = (
    ('S', 'Solteiro'),
    ('C', 'Casado'),
    ('D', 'Divorciado'),
    ('V', 'Viúvo'),
    ('O', 'Outro'),
)


# status of the Candidate Aproval to the dashboard
USER_STATUS_CHOICES = (
    ('aproved', 'Aprovado'),
    ('denied ', 'Não Aprovado'),
    ('pending', 'Aguardando Aprovação'),
)

# Kind of activity or function of the user to the candidate or campaign
USER_ROLES_CHOICES = (
    ('subscriber', 'Assinante'),
    ('agency', 'Agência de Marketing'),
    ('consultor', 'Consultor de Campanha'),
    ('external_contractor', 'Contratado Externo'),
    ('internal_employee', 'Empregado Interno'),
    ('outsourced', 'Terceirizado'),
    ('voluntary', 'Voluntário'),
)


# This will represent an user account profile entity (will substitute the Profile Model bellow)
class Usuario(models.Model):
    user = models.OneToOneField(User, null=False, blank=False, on_delete=models.CASCADE)
    gender = models.CharField('Gênero', max_length=1, choices=GENDER_CHOICES['physical'] + GENDER_CHOICES['legal'],
                              null=True)
    marital_status = models.CharField("Estado Civil", max_length=1, choices=ESTADO_CIVIL_CHOICES, null=True)
    cpf = models.CharField('CPF', max_length=11, unique=True, null=True, blank=True)    # Document ID in Brazil
    birthday_date = models.TextField('Data de Nascimento', null=True, blank=True)
    # todo to implement autofill address - https://github.com/staticdev/django-cep
    cep = models.CharField("CEP", max_length=9, blank=True, null=True)  # The Brazilian zipCode
    estado = models.CharField("UF", max_length=2, blank=True, null=True)    # Federal State (in dashboard_estado table)
    cidade = models.CharField("Cidade", max_length=255, blank=True, null=True)  # city
    bairro = models.CharField("Bairro", max_length=255, blank=True, null=True)  # neiborhood
    address = models.CharField("Endereço", max_length=255, blank=True, null=True)
    company = models.CharField("Endereço", max_length=255, blank=True, null=True)
    cellPhone = models.CharField(blank=True, null=True, max_length=17, validators=[phone_validators])
    landlinePhone = models.CharField("Telefone Fixo", max_length=17, blank=True, null=True,
                                     validators=[phone_validators])
    email_verified = models.NullBooleanField(null=True)
    cellPhone_verified = models.BooleanField(default=False)
    user_political_party = models.CharField(max_length=50, blank=True, null=True)
    user_profile_photo = models.ImageField(upload_to='images/users', verbose_name='foto', null=True, blank=True)
    created_date = models.DateField(auto_now=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    # Information of the access rights and roles of User to the candidate

    user_status = models.CharField("Status", max_length=40, choices=USER_STATUS_CHOICES)
    # user_role = models.CharField("Tipo de Acesso", max_length=40, choices=USER_ROLES_CHOICES)
    user_roles_list = models.ForeignKey(
        'candidato.UserRolesList', blank=True, null=True, related_name='user_roles_list_in_usuario',
        on_delete=models.CASCADE)
    candidates = models.ManyToManyField(Candidate, blank=True)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Usuario.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.usuario.save()


@receiver(pre_delete, sender=User)
def delete_user_profile(sender, instance, **kwargs):
    global event_hook_depth
    event_hook_depth += 1
    if event_hook_depth < 3:
        try:
            instance.usuario.delete()
        except Exception as e:
            print('exception occurred!', e)
        event_hook_depth = 0
    return


@receiver(pre_delete, sender=Usuario)
def delete_dashboard_usuario(sender, instance, **kwargs):
    global event_hook_depth
    event_hook_depth += 1
    if event_hook_depth < 3:
        try:
            instance.user.delete()
        except Exception as e:
            print('exception occurred!', e)
        event_hook_depth = 0
    return

templates/acc_active_email.html
{% autoescape off %}
Olá {{ user.username }},
Por favor clique no link abaixo para confirmar seu cadastro.
http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

templates/authorization.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- saved from url=(0071) -->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

  <title>SCOPO Online - Welcome</title>
  <meta name="viewport" content="width=device-width">
  <style type="text/css">
    @media only screen and (max-width: 550px), screen and (max-device-width: 550px) {
      body[yahoo] .buttonwrapper {
        background-color: transparent !important;
      }

      body[yahoo] .button {
        padding: 0 !important;
      }

      body[yahoo] .button a {
        background-color: #1bbae1;
        padding: 15px 25px !important;
      }
    }

    @media only screen and (min-device-width: 601px) {
      .content {
        width: 600px !important;
      }

      .col387 {
        width: 387px !important;
      }
    }
  </style>
</head>
<body bgcolor="#2f5c7a" style="margin: 0; padding: 0; background: rgb(47, 92, 122);" yahoo="fix">
<!--[if (gte mso 9)|(IE)]>
<table width="600" align="center" cellpadding="0" cellspacing="0" border="0">
  <tr>
    <td>
<![endif]-->
<table align="center" border="0" cellpadding="0" cellspacing="0"
       style="border-collapse: collapse; width: 100%; max-width: 600px;" class="content">
  <tbody>
    <tr>
      <td style="padding: 15px 10px 15px 10px;">
        <table border="0" cellpadding="0" cellspacing="0" width="100%">
          <tbody>
          <tr>
            <td align="center" style="color: #aaaaaa; font-family: Arial, sans-serif; font-size: 12px;">
              Não consegue visualizar este email? <a href="http://{{ domain }}/browser_view/?id={{ user.id }}"
                                                     style="color: #1bbae1;">Veja em seu Navegador</a>
            </td>
          </tr>
          </tbody>
        </table>
      </td>
    </tr>
    <tr>
      <td align="center" bgcolor="#f5f5f5"
          style="padding: 20px 20px 20px 20px; color: #ffffff; font-family: Arial, sans-serif; font-size: 36px; font-weight: bold;">
        <img src="http://scopoonline.com/images/SCOPO_300px.png" alt="SCOPO Online" style="display:block;">
      </td>
    </tr>
    <tr>
      <td align="center" bgcolor="#ffffff"
          style="padding: 40px 20px 40px 20px; color: #555555; font-family: Arial, sans-serif; font-size: 20px; line-height: 30px; border-bottom: 1px solid #f6f6f6;">
        <p>Olá {{ user.first_name }}, obrigado pelo seu registro no SCOPO.</p>
        <strong> Estamos quase lá...</strong><br/>
        <p>Clique no botão abaixo para ativar sua conta</p>
      </td>
    </tr>
    <tr>
      <td align="center" bgcolor="#f9f9f9" style="padding: 30px 20px 30px 20px; font-family: Arial, sans-serif;">
        <table bgcolor="#1bbae1" border="0" cellspacing="0" cellpadding="0" class="buttonwrapper">
          <tbody>
          <tr>
            <td align="center" height="50"
                style=" padding: 0 25px 0 25px; font-family: Arial, sans-serif; font-size: 16px; font-weight: bold;"
                class="button">
              <a href="http://{{ domain }}{% url 'activate' uidb64=uid token=token %}"
                 style="color: #ffffff; text-align: center; text-decoration: none;">Ativar Conta</a>
            </td>
          </tr>
          </tbody>
        </table>
      </td>
    </tr>
    <tr>
      <td align="center" bgcolor="#dddddd"
          style="padding: 15px 10px 15px 10px; color: #555555; font-family: Arial, sans-serif; font-size: 12px; line-height: 18px;">
        <strong>Directnet / Neoplace Inc.</strong><br>Av. Sete de Setembro, 4698 • Cj.2201 • Curitiba, PR • CEP:
        80240-0000
      </td>
    </tr>
    <tr>
      <td style="padding: 15px 10px 15px 10px;">
        <table border="0" cellpadding="0" cellspacing="0" width="100%">
          <tbody>
          <tr>
            <td align="center" width="100%" style="color: #999999; font-family: Arial, sans-serif; font-size: 12px;">
              2018-19 © <a href="http://portaldocandidato.inf.br/" style="color: #1bbae1;">SCOPO Online</a>
            </td>
          </tr>
          </tbody>
        </table>
      </td>
    </tr>
  </tbody>
</table>
<!--[if (gte mso 9)|(IE)]>
        </td>
    </tr>
</table>
<![endif]-->

</body>
</html>

templates/cities_drop_down.html
{#<option value="">---------</option>#}
{% for city in cities %}
<option value="{{ city.0 }}">{{ city.1 }}</option>
{% endfor %}

templates/not_active.html
{% extends '_base.html' %}
{% load staticfiles %}

{% block content %}
  <div class="page-container">

    <div class="modal-dialog">
      <div class="login-form">
        <div class="block">
          <div class="block-title text-center">
            <h2>Notificação</h2>
          </div>
          <div class="alert alert-warning" style="display: inline-flex">
            <i class="icon-warning" style="font-size: 33px;margin-right: 10px;"></i>
            <span>
              Seu registro no scopo.online foi efetuado com sucesso. Parabéns. Por favor, aguarde sua aprovação pelo seu candidato.
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/profile.html
{% extends '_base.html' %}
{% load staticfiles %}

{% block content %}
  <div class="page-container">

    <!--Main layout-->
    <div class="container">

      <!--First row-->
      <div class="row wow fadeIn" data-wow-delay="0.4s" style="margin-top: 50px;">

        <fieldset class="content-group text-center">
          <legend class="text-bold">Account Settings</legend>
        </fieldset>

      </div>

      <!--/.First row-->

      <!--Second row-->
      <form action="{% url 'profile' %}" method="post" onsubmit="return validateForm();"
            class="form-horizontal form-bordered"
            style="max-width: 700px;margin: auto;margin-bottom: 50px"
            name="user-form">
        {% csrf_token %}
        <input type="hidden" name="gender" value="{{ profile_form.gender.value }}">
        <input type="hidden" name="marital_status" value="{{ profile_form.marital_status.value }}">
        <input type="hidden" name="cpf" value="{{ profile_form.cpf.value }}">
        <input type="hidden" name="birthday_date" value="{{ profile_form.birthday_date.value }}">
        <input type="hidden" name="bairro" value="{{ profile_form.bairro.value }}">
        <input type="hidden" name="landlinePhone" value="{{ profile_form.landlinePhone.value }}">
        <input type="hidden" name="user_political_party" value="{{ profile_form.user_political_party.value }}">
        <input type="hidden" name="user_roles_list" value="{{ profile_form.user_roles_list.value }}">
        <div class="form-group">
          <label class="col-md-3 control-label" for="username">User Name</label>
          <div class="col-md-9">
            <input type="text"
                   value="{{ request.user.username }}"
                   name="username"
                   readonly
                   class="form-control" placeholder="User Name">
          </div>
        </div>
        <div class="form-group">
          <label class="col-md-3 control-label" for="old_password">Current Password</label>
          <div class="col-md-9">
            <input type="password"
                   name="old_password"
                   class="form-control" placeholder="Current Password">
          </div>
        </div>
        <div class="form-group">
          <label class="col-md-3 control-label" for="new_password1">New Password</label>
          <div class="col-md-9">
            <input type="password"
                   name="new_password1"
                   class="form-control" placeholder="New Password">
          </div>
        </div>
        <div class="form-group">
          <label class="col-md-3 control-label" for="new_password2">New Password Confirmation</label>
          <div class="col-md-9">
            <input type="password"
                   name="new_password2"
                   class="form-control" placeholder="New Password Confirmation">
          </div>
        </div>

        <div class="form-group">
          <label class="col-md-3 control-label" for="first_name">First Name</label>
          <div class="col-md-9">
            <input type="text"
                   value="{{ request.user.first_name }}"
                   name="first_name"
                   class="form-control" placeholder="First Name">
          </div>
        </div>
        <div class="form-group">
          <label class="col-md-3 control-label" for="last_name">Last Name</label>
          <div class="col-md-9">
            <input type="text"
                   value="{{ request.user.last_name }}"
                   name="last_name"
                   class="form-control" placeholder="Last Name">
          </div>
        </div>
        <div class="form-group">
          <label class="col-md-3 control-label" for="email">Email</label>
          <div class="col-md-9">
            <input type="email"
                   value="{{ request.user.email }}"
                   name="email"
                   class="form-control"
                   placeholder="Enter Email">
            {# <span class="help-block">Please enter your email</span>#}
          </div>
        </div>
        <div class="form-group">
          <label class="col-md-3 control-label" for="company">Company</label>
          <div class="col-md-9">
            <input type="text"
                   value="{{ profile_form.company.value }}"
                   name="company"
                   class="form-control" placeholder="Enter Company">
          </div>
        </div>
        <div class="form-group">
          <label class="col-md-3 control-label" for="estado">State :</label>
          <div class="col-md-9">
            {{ profile_form.estado }}
          </div>
        </div>
        <div class="form-group">
          <label class="col-md-3 control-label" for="example-select">City :</label>
          <div class="col-md-9">
            <select class="form-control" id="id_cidade" name="cidade" title="Cidade">
              {% for city in cities %}
                {% if selected_city  ==  city.0 %}
                  <option data="{{ city.1 }}" value="{{ city.0 }}" selected>{{ city.1 }}</option>
                {% else %}
                  <option value="{{ city.0 }}">{{ city.1 }}</option>
                {% endif %}
              {% endfor %}
            </select>
          </div>
        </div>
        <div class="form-group">
          <label class="col-md-3 control-label" for="cep">Zipcode</label>
          <div class="col-md-9">
            <input type="text"
                   value="{{ profile_form.cep.value }}"
                   name="cep"
                   class="form-control zip-field" placeholder="Enter Zipcode">
          </div>
        </div>
        <div class="form-group">
          <label class="col-md-3 control-label" for="address">Address</label>
          <div class="col-md-9">
            <input type="text"
                   value="{{ profile_form.address.value }}"
                   name="address"
                   id="address"
                   class="form-control typeahead" placeholder="Enter an address">
          </div>
        </div>

        <div id="map" class="map-wrapper"></div>
        <div class="form-group" style="margin-top: 30px;">
          <label class="col-md-3 control-label" for="cellPhone">Telephone</label>
          <div class="col-md-9">
            <input type="text"
                   id="telephone"
                   value="{{ profile_form.cellPhone.value }}"
                   name="cellPhone"
                   class="form-control" placeholder="Enter telephone number">
          </div>
        </div>

        <hr>
        <div class="row prepend-top-default append-bottom-default" style="margin-bottom: 15px;">
          <div class="col-md-8">
            {% if messages %}
              <ul class="messages">
                {% for message in messages %}
                  <li{% if message.tags %}
                    class="alert alert-{{ message.tags }} alert-styled-left"{% endif %}>{{ message }}
                  </li>
                {% endfor %}
              </ul>
            {% endif %}
          </div>
          <div class="col-md-4 text-right" style="margin-top: 15px;">
            <input type="submit" name="commit" value="Update Profile" class="btn btn-success">
          </div>
        </div>
        {% if user_form.errors %}
          {% for field in user_form %}
            {% for error in field.errors %}
              <div class="alert alert-danger">
                {{ field.label_tag }}
                <strong>{{ error|escape }}</strong>
              </div>
            {% endfor %}
          {% endfor %}

          {% for error in user_form.non_field_errors %}
            <div class="alert alert-danger">
              <strong>{{ error|escape }}</strong>
            </div>
          {% endfor %}
        {% endif %}

        {% if profile_form.errors %}
          {% for field in profile_form %}
            {% for error in field.errors %}
              <div class="alert alert-danger">
                {{ field.label_tag }}
                <strong>{{ error|escape }}</strong>
              </div>
            {% endfor %}
          {% endfor %}

          {% for error in profile_form.non_field_errors %}
            <div class="alert alert-danger">
              <strong>{{ error|escape }}</strong>
            </div>
          {% endfor %}
        {% endif %}
      </form>
      <!--/.Second row-->

    </div>
    <!--/.Main layout-->

  </div>
  <div class="loder-layer" id="loading">
    <div class="loder-center">
      <div class="loader"></div>
      <h3><b>Loading...</b></h3>
    </div>
  </div>
  {% comment %}https://developers.google.com/maps/documentation/javascript/get-api-key{% endcomment %}
  <script type="text/javascript" src='https://maps.googleapis.com/maps/api/js?key=AIzaSyDk--U-aOtHrezSQ9oM8ikjUikreFAXyQc&sensor=false&libraries=places'></script>
  <script type="text/javascript" src="{% static 'js/plugins/forms/inputs/typeahead/typeahead.bundle.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/plugins/pickers/location/typeahead_addresspicker.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/plugins/pickers/location/autocomplete_addresspicker.js' %}"></script>
  <script src="{% static 'cep/js/cep.js' %}"></script>
  <script src="{% static 'update_profile.js' %}"></script>
  <script>
    // Basic initialization, based on Bloodhound
    var addressPicker = new AddressPicker({
      map: {
        id: '#map'
      }
    });

    // instantiate the typeahead UI
    $('#address').typeahead(null, {
      displayKey: 'description',
      source: addressPicker.ttAdapter()
    });

    // Bind some event to update map on autocomplete selection
    $('#address').bind('typeahead:selected', addressPicker.updateMap);
    $('#address').bind('typeahead:cursorchanged', addressPicker.updateMap);
  </script>
{% endblock %}